name: Deploy static contents to Pages for zawa-ch.stellar-drop.info
on:
  # 指定されたブランチにpushされたときにトリガー
  push:
    branches: ["zawa-ch.stellar-drop.info/release"]

  # マニュアル操作によるトリガー
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: zawa-ch.stellar-drop.info/release
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22.x
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: pnpm install
      - name: Build pages
        run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4